- name: {{ name }}
  hosts: all
  become: false
  tasks:
    - name: kill controller process
      shell: "pkill -f 'python -m infscale start controller'"
      ignore_errors: true

    - name: kill agent processes
      shell: "pkill -f 'python -m infscale start agent'"
      ignore_errors: true
